# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EsRequisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codpre', models.CharField(max_length=6)),
                ('cod', models.CharField(max_length=6)),
            ],
            options={
                'managed': False,
                'db_table': 'es_requisito',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_teoria', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('h_prac', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('h_lab', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('fecha_vigtrim', models.CharField(blank=True, max_length=8, null=True)),
                ('fecha_vigano', models.IntegerField(blank=True, null=True)),
                ('obj_g', models.CharField(blank=True, max_length=1000, null=True)),
                ('obj_e', models.CharField(blank=True, max_length=1000, null=True)),
                ('contenidos', models.CharField(blank=True, max_length=1000, null=True)),
                ('estrategias', models.CharField(blank=True, max_length=1000, null=True)),
                ('estrat_eval', models.CharField(blank=True, max_length=1000, null=True)),
                ('fuentes', models.CharField(blank=True, max_length=1000, null=True)),
                ('cronograma', models.CharField(blank=True, max_length=1000, null=True)),
                ('sinoptico', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'programa',
            },
        ),
        migrations.CreateModel(
            name='RProgPl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idplanilla', models.IntegerField()),
                ('idprograma', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'r_prog_pl',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcoord', models.CharField(max_length=50)),
                ('porasignar', models.BooleanField()),
                ('porvalidard', models.BooleanField()),
                ('porrevisarp', models.BooleanField()),
                ('rechazadoc', models.BooleanField()),
                ('validadoc', models.BooleanField()),
                ('enviadod', models.BooleanField()),
                ('devueltodace', models.BooleanField()),
                ('fechaelab', models.DateField()),
                ('tipo_solicitud', models.CharField(max_length=20)),
                ('subtipo_solicitud', models.CharField(max_length=30)),
                ('nivel', models.CharField(max_length=20)),
                ('cod', models.CharField(max_length=7)),
                ('cod_anterior', models.CharField(blank=True, max_length=7, null=True)),
                ('denominacion', models.CharField(max_length=70)),
                ('creditos', models.DecimalField(decimal_places=0, max_digits=2)),
                ('tipo_aula', models.CharField(max_length=20)),
                ('hteoria', models.BooleanField()),
                ('hpractica', models.BooleanField()),
                ('hlab', models.BooleanField()),
                ('trime', models.CharField(max_length=8)),
                ('ano', models.CharField(max_length=4)),
                ('accion', models.CharField(max_length=20)),
                ('afecta_carrera', models.CharField(max_length=35)),
                ('trimestrep', models.BooleanField()),
                ('requisito_cre', models.BooleanField()),
                ('permiso_coord', models.BooleanField()),
                ('tipo_materia', models.CharField(max_length=20)),
                ('clase_materia', models.CharField(max_length=25)),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('vigente', models.NullBooleanField()),
                ('validadodace', models.BooleanField()),
                ('especial', models.BooleanField()),
                ('imparticion', models.CharField(max_length=15)),
                ('usbidec', models.CharField(blank=True, max_length=50, null=True)),
                ('obsanul', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'solicitud',
            },
        ),
    ]
