# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 20:03
from __future__ import unicode_literals

import SIGPAEHistorico.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('docfile', models.FileField(upload_to='', validators=[SIGPAEHistorico.validators.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='ventana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
