# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 02:16
from __future__ import unicode_literals

import SIGPAEHistorico.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAEHistorico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultapae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('year', models.IntegerField(default=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('docfile', models.FileField(upload_to='static/uploads/pdf', validators=[SIGPAEHistorico.validators.validate_file_extension])),
                ('doctext', models.TextField(blank=True, default='')),
                ('codigo_programa', models.CharField(blank=True, default='', max_length=8)),
                ('creditos', models.IntegerField(default=0, null=True, validators=[SIGPAEHistorico.validators.validate_credits])),
                ('tituloP', models.CharField(blank=True, default='', max_length=60)),
                ('fechaP', models.IntegerField(blank=True, null=True, validators=[SIGPAEHistorico.validators.validate_year])),
                ('periodoP', models.CharField(blank=True, choices=[('aj', 'sep-dic'), ('sd', 'ene-mar'), ('em', 'abr-jul'), ('verano', 'verano')], default='', max_length=2)),
                ('h_teo', models.IntegerField(blank=True, default=0, null=True, validators=[SIGPAEHistorico.validators.validate_hours])),
                ('h_prac', models.IntegerField(blank=True, default=0, null=True, validators=[SIGPAEHistorico.validators.validate_hours])),
                ('h_lab', models.IntegerField(blank=True, default=0, null=True, validators=[SIGPAEHistorico.validators.validate_hours])),
                ('departamento', models.CharField(blank=True, default='', max_length=70)),
                ('coordinacion', models.CharField(blank=True, default='', max_length=70)),
                ('contSinop', models.TextField(blank=True, default='')),
                ('FuenteInfo', models.TextField(blank=True, default='')),
                ('objetivos', models.TextField(blank=True, default='')),
                ('requisito', models.TextField(blank=True, default='')),
                ('estrategias_meto', models.TextField(blank=True, default='')),
                ('estrategias_eval', models.TextField(blank=True, default='')),
            ],
        ),
    ]
