# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 17:16
from __future__ import unicode_literals

import SIGPAEHistorico.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAEHistorico', '0002_auto_20170216_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dochtml',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='static/uploads/pdf', validators=[SIGPAEHistorico.validators.validate_file_extension]),
        ),
    ]
