# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAEHistorico', '0002_consultapae_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Adepartamento',
            field=models.CharField(blank=True, choices=[('1', '---------'), ('2', 'División Ciencias Físicas y Matemáticas'), ('3', 'División Ciencias Sociales y Humanidades'), ('4', 'División Ciencias Biológicas'), ('5', 'División Ciencias y Tecnologías Administrativas e Industriales')], default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='document',
            name='departamento',
            field=models.CharField(blank=True, choices=[('1', '---------'), ('2', 'Física'), ('3', 'Química'), ('4', 'Mecánica'), ('5', 'Matemáticas Puras y Aplicadas'), ('6', 'Computo Científico y Estadística'), ('7', 'Electrónica y Circuitos'), ('8', 'Termodinámica y Fenómenos de Transferencia'), ('9', 'Conversión y Transporte de Energía'), ('10', 'Procesos y Sistemas'), ('11', 'Ciencias de los Materiales'), ('12', 'Ciencias de la Tierra'), ('13', 'Ciencia y Tecnología del Comportamiento'), ('14', 'Lengua y Literatura'), ('15', 'Ciencias Económicas y Administrativas'), ('16', 'Idiomas'), ('17', 'Filosofía'), ('18', 'Ciencias Sociales'), ('19', 'Arquitectura y Artes Plásticas'), ('20', 'Planificación Urbana'), ('21', 'Biología Celular'), ('22', 'Estudios Ambientales'), ('23', 'Biología de Organismos'), ('24', 'Tecnología de Procesos Biológicos y Bioquímicos'), ('25', 'Tecnología de Servicios'), ('26', 'Tecnología Industrial'), ('27', 'Formación General y Ciencias Básicas')], default='', max_length=70),
        ),
    ]
