# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAEHistorico', '0003_auto_20170315_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultapae',
        ),
    ]
