# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAEHistorico', '0004_auto_20170314_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='FuenteInfo',
        ),
        migrations.RemoveField(
            model_name='document',
            name='codigo_Programa',
        ),
        migrations.RemoveField(
            model_name='document',
            name='contSinop',
        ),
        migrations.RemoveField(
            model_name='document',
            name='coordinacion',
        ),
        migrations.RemoveField(
            model_name='document',
            name='creditos',
        ),
        migrations.RemoveField(
            model_name='document',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='document',
            name='estrategias_eval',
        ),
        migrations.RemoveField(
            model_name='document',
            name='estrategias_meto',
        ),
        migrations.RemoveField(
            model_name='document',
            name='fechaP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='h_lab',
        ),
        migrations.RemoveField(
            model_name='document',
            name='h_prac',
        ),
        migrations.RemoveField(
            model_name='document',
            name='h_teo',
        ),
        migrations.RemoveField(
            model_name='document',
            name='objetivos',
        ),
        migrations.RemoveField(
            model_name='document',
            name='periodoP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='requisito',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tituloP',
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
