# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 19:47
from __future__ import unicode_literals

import SIGPAEHistorico.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAEHistorico', '0006_auto_20170315_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tituloP',
            field=models.CharField(blank=True, default='', max_length=60, validators=[SIGPAEHistorico.validators.validate_year]),
        ),
    ]
