# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 19:48
from __future__ import unicode_literals

import SIGPAEHistorico.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAEHistorico', '0007_auto_20170315_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fechaP',
            field=models.IntegerField(blank=True, null=True, validators=[SIGPAEHistorico.validators.validate_year]),
        ),
        migrations.AlterField(
            model_name='document',
            name='tituloP',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
