# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 19:53
from __future__ import unicode_literals

import SIGPAEHistorico.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAEHistorico', '0008_auto_20170315_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='h_lab',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[SIGPAEHistorico.validators.validate_hours]),
        ),
        migrations.AlterField(
            model_name='document',
            name='h_prac',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[SIGPAEHistorico.validators.validate_hours]),
        ),
        migrations.AlterField(
            model_name='document',
            name='h_teo',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[SIGPAEHistorico.validators.validate_hours]),
        ),
    ]
