# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAEHistorico', '0009_auto_20170315_1953'),
        ('SIGPAEHistorico', '0007_auto_20170314_2154'),
    ]

    operations = [
    ]
