# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 01:37
from __future__ import unicode_literals

import SIGPAEHistorico.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAEHistorico', '0010_merge_20170316_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultapae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('year', models.IntegerField(default=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='FuenteInfo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='codigo_programa',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='document',
            name='contSinop',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='coordinacion',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='document',
            name='creditos',
            field=models.IntegerField(default=0, null=True, validators=[SIGPAEHistorico.validators.validate_credits]),
        ),
        migrations.AlterField(
            model_name='document',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='document',
            name='estrategias_eval',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='estrategias_meto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='fechaP',
            field=models.IntegerField(blank=True, null=True, validators=[SIGPAEHistorico.validators.validate_year]),
        ),
        migrations.AlterField(
            model_name='document',
            name='h_lab',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[SIGPAEHistorico.validators.validate_hours]),
        ),
        migrations.AlterField(
            model_name='document',
            name='h_prac',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[SIGPAEHistorico.validators.validate_hours]),
        ),
        migrations.AlterField(
            model_name='document',
            name='h_teo',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[SIGPAEHistorico.validators.validate_hours]),
        ),
        migrations.AlterField(
            model_name='document',
            name='objetivos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='periodoP',
            field=models.CharField(blank=True, choices=[('aj', 'sep-dic'), ('sd', 'ene-mar'), ('em', 'abr-jul'), ('verano', 'verano')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='document',
            name='requisito',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='tituloP',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
